task_post/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    # path("mainapp/", RedirectView.as_view(url="mainapp/")),
    path("", include("mainapp.urls")),
]

task_post/mainapp/urls.py
from mainapp import views
from rest_framework.routers import DefaultRouter
from django.urls import path, include

from mainapp.views import LetterModelViewSet, ParcelModelViewSet

router = DefaultRouter()
router.register('letter', LetterModelViewSet)
router.register('parcel', ParcelModelViewSet)


urlpatterns = [
    path("", views.MainPageView.as_view(), name="index"),
    path("index", views.MainPageView.as_view()),
    path("letter_create/", views.LetterCreateView.as_view(), name="letter_create"),
    path("letter_list/", views.LetterListView.as_view(), name="letters_list"),
    path("letter_update/<int:pk>/", views.LetterUpdateView.as_view(), name="letter_update"),
    path("letter_view/<int:pk>/", views.LetterView.as_view(), name="letter_view",),
    path("letter_delete/<int:pk>/", views.LetterDeleteView.as_view(), name="letter_delete", ),
    path("parcel_create/", views.ParcelCreateView.as_view(), name="parcel_create"),
    path("parcel_list/", views.ParcelListView.as_view(), name="parcels_list"),
    path("parcel_update/<int:pk>/", views.ParcelUpdateView.as_view(), name="parcel_update"),
    path("parcel_view/<int:pk>/", views.ParcelView.as_view(), name="parcel_view", ),
    path("parcel_delete/<int:pk>/", views.ParcelDeleteView.as_view(), name="parcel_delete", ),
    path('api/', include(router.urls)),
]

task_post/mainapp/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

from config import settings
from config.settings import PARCEL_TYPES, LETTER_TYPES


def get_letter_types():
    return {i: i for i in settings.LETTER_TYPES}


def get_parcel_types():
    return {i: i for i in settings.PARCEL_TYPES}


class PostItem(models.Model):
    sender_name = models.CharField(max_length=128, blank=False)
    sender_surname = models.CharField(max_length=128, blank=False)
    from_address = models.CharField(max_length=128, blank=False)
    to_address = models.CharField(max_length=128, blank=False)
    from_index = models.PositiveIntegerField(blank=False)
    to_index = models.PositiveIntegerField(blank=False)

    class Meta:
        abstract = True


class Letter(PostItem):
    letter_type = models.IntegerField(choices=LETTER_TYPES, default=1)
    letter_weight = models.PositiveIntegerField(default=0)

    objects = models.Manager()


class Parcel(PostItem):
    phone = PhoneNumberField(blank=True)
    parcel_type = models.IntegerField(choices=PARCEL_TYPES, default=1)
    price = models.DecimalField(max_digits=6, decimal_places=2)

    objects = models.Manager()

task_post/mainapp/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import (CreateView, DeleteView, ListView,
                                  TemplateView, UpdateView, View, DetailView)
from rest_framework.viewsets import ModelViewSet

from mainapp.models import Letter, Parcel

from mainapp.serializer import LetterModelSerializer, ParcelModelSerializer


class MainPageView(TemplateView):
    template_name = "mainapp/index.html"


class LetterCreateView(CreateView):
    template_name = "mainapp/letter_form.html"
    model = Letter
    fields = ['sender_name',
              'sender_surname',
              'from_address',
              'to_address',
              'from_index',
              'to_index',
              'letter_type',
              'letter_weight',
              ]

    def get_success_url(self):
        return reverse('letters_list')


class LetterListView(ListView):
    model = Letter
    template_name = "letter_list.html"

    def get_queryset(self):
        return Letter.objects.all()


class LetterUpdateView(UpdateView):
    template_name_suffix = "_update_form"
    model = Letter
    fields = ['sender_name',
              'sender_surname',
              'from_address',
              'to_address',
              'from_index',
              'to_index',
              'letter_type',
              'letter_weight',
              ]

    def get_success_url(self):
        pk = self.kwargs["pk"]
        return reverse("letter_view", kwargs={"pk": pk})


class LetterView(DetailView):
    model = Letter


class LetterDeleteView(DeleteView):
    model = Letter
    template_name = "mainapp/letter_confirm_delete.html"

    def get_success_url(self):
        return reverse('letters_list')


class ParcelCreateView(CreateView):
    template_name = "mainapp/parcel_form.html"
    model = Parcel
    fields = ['sender_name',
              'sender_surname',
              'from_address',
              'to_address',
              'from_index',
              'to_index',
              'phone',
              'parcel_type',
              'price',
              ]

    def get_success_url(self):
        return reverse('parcels_list')


class ParcelListView(ListView):
    model = Parcel
    template_name = "parcel_list.html"

    def get_queryset(self):
        return Parcel.objects.all()


class ParcelUpdateView(UpdateView):
    template_name_suffix = "_update_form"
    model = Parcel
    fields = ['sender_name',
              'sender_surname',
              'from_address',
              'to_address',
              'from_index',
              'to_index',
              'phone',
              'parcel_type',
              'price',
              ]

    def get_success_url(self):
        pk = self.kwargs["pk"]
        return reverse("parcel_view", kwargs={"pk": pk})


class ParcelView(DetailView):
    model = Parcel


class ParcelDeleteView(DeleteView):
    model = Parcel
    template_name = "mainapp/parcel_confirm_delete.html"

    def get_success_url(self):
        return reverse('parcels_list')


class LetterModelViewSet(ModelViewSet):
    queryset = Letter.objects.all()
    serializer_class = LetterModelSerializer


class ParcelModelViewSet(ModelViewSet):
    queryset = Parcel.objects.all()
    serializer_class = ParcelModelSerializer

task_post/templates/includes/inc_footer.html
{# Блок Footer #}
{% load static %}
<footer class="container" style="margin-top: 30px;">
    <div class="content">
                <div style="margin-bottom: 8px; color:#222; background-color: dodgerblue; min-height:40px; padding: 20px;">
                    © 2024 Vladimir Malchevskiy
                </div>
    </div>
</footer>
{# Конец Блок Footer #}

task_post/templates/includes/inc_menu.html
{# Блок меню #}
{% load static %}
<div class="container" style="margin-bottom: 30px;">
    <div class="content">
                <div style="margin-bottom: 8px; color:#222; background-color: dodgerblue; min-height:40px; padding: 20px;">
                        <h3> FGUP GAMMA </h3>
                </div>
    </div>
</div>
{# КОНЕЦ Блок меню #}

task_post/templates/mainapp/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">

    {% block title %}
        <title>Post_web_site</title>
    {% endblock %}
    {% block css %}
        <link rel="stylesheet" type="text/css"
              href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css"
              href="{% static 'css/style.css' %}">
        <link rel="stylesheet" type="text/css"
            href="{% static 'css/fontawesome.min.css' %}">
    {% endblock %}
    {% block js %}
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    {% endblock %}

</head>
<body>
<div class="container">

    {% block menu %}
        {% include 'includes/inc_menu.html' %}
    {% endblock %}

    {% block list %}

    {% endblock %}

    {% block content %}

    {% endblock %}

</div>
</body>

    {% block footer %}
        {% include 'includes/inc_footer.html' %}
    {% endblock %}

</html>

task_post/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
<div class="container content">
<h1> Welcome to POST web-page!</h1>
  <ul class="list-group">

            <li class="list-group-item">
                <a href="{% url 'letters_list' %}"
                   style="text-decoration: none"> Работа с письмами </a>
            </li>
                  <li class="list-group-item">
                <a href="{% url 'parcels_list' %}"
                   style="text-decoration: none"> Работа с посылками </a>
            </li>

        </ul>
</div>

{% endblock %}

task_post/templates/mainapp/letter_confirm_delete.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
<div class="container content">
<h1> Confirm Letter Delete </h1>
<br>
<form method="post">{% csrf_token %}

<p>Are you sure you want to delete Letter No.{{ object.id }}  of Type: {{object.get_letter_type_display }}"?</p>

    <input type="submit" class="mt-4 btn btn-primary" style="margin: 10px;" value="Удалить">
    <a href="{% url 'letters_list' %}"
                   class="mt-4 btn btn-primary" style="margin: 10px;" > Отменить </a>
        <a href="{% url 'index' %}" class="mt-4 btn btn-primary" style="margin: 10px;"> На главную </a>
</form>
</div>
{% endblock %}

task_post/templates/mainapp/letter_detail.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
<div class="container content">
<h1> Letter Details </h1>
<br>

<h1>Letter {{ object.id }}</h1>
<p> from : {{ object.sender_name }} {{ object.sender_surname }}</p>
<p> weight: {{ object.weight }}</p>
<p> from_address: {{ object.from_address }}</p>
<p> to_address: {{ object.to_address }}</p>
<p> Letter Type: {{ object.get_letter_type_display  }}</p>

    <a href="{% url 'index' %}"
                   class="mt-4 btn btn-primary" style="margin: 10px;"> На главную </a>
  <a href="{% url 'letters_list' %}"
  class="mt-4 btn btn-primary" style="margin: 10px;">Обратно</a>
  <a href="{% url 'letter_update' object.id %}"
               class="mt-4 btn btn-primary" style="margin: 10px;">Редактировать</a>
  <a href="{% url 'letter_delete' object.id %}"
               class="mt-4 btn btn-primary" style="margin: 10px;">Удалить</a>
    </div>
{% endblock %}

task_post/templates/mainapp/letter_form.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
<div class="container content">
<h1> Letter Create Form </h1>
<br>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Создать" class="mt-4 btn btn-primary" style="margin: 10px;">
     <a href="{% url 'letters_list' %}"
                   class="mt-4 btn btn-primary" style="margin: 10px;"> Отменить </a>
</form>
</div>
{% endblock %}

task_post/templates/mainapp/letter_list.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block content %}
<div class="container content">
  <h1>Letter List</h1>
  <br>
  {% if letter_list %}
    <ul>
      {% for letter in letter_list %}
      <li>
        <a href="{% url 'letter_view' letter.id  %}">Letter{{letter.id}}  From: {{ letter.sender_name }} {{ letter.sender_surname }}</a>
        ({{letter.get_letter_type_display }})
      </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no letters to show.</p>
  {% endif %}
   <a href="{% url 'letter_create' %}"
               class="mt-4 btn btn-primary" style="margin: 10px;"">Новое Письмо</a>
    <a href="{% url 'index' %}"
                   class="mt-4 btn btn-primary" style="margin: 10px;"> На главную </a>
</div>
{% endblock %}

task_post/templates/mainapp/letter_update_form.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
<div class="container content">
<h1> Letter Update Form </h1>
<br>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить" class="mt-4 btn btn-primary" style="margin: 10px;">
     <a href="{% url 'letters_list' %}"
                   class="mt-4 btn btn-primary" style="margin: 10px;"> Отменить </a>
</form>
</div>
{% endblock %}

task_post/templates/mainapp/parcel_confirm_delete.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
<div class="container content">
<h1> Confirm Parcel Delete </h1>
<br>
<form method="post">{% csrf_token %}

<p>Are you sure you want to delete Parcel No.{{ object.id }}  of Type: {{object.get_parcel_type_display }}"?</p>

    <input class="mt-4 btn btn-primary" style="margin: 10px;" type="submit" value="Удалить">
    <a href="{% url 'parcels_list' %}"
                   class="mt-4 btn btn-primary" style="margin: 10px;"> Отменить </a>
        <a href="{% url 'index' %}"
                   class="mt-4 btn btn-primary" style="margin: 10px;"> На главную </a>
</form>
</div>
{% endblock %}

task_post/templates/mainapp/parcel_detail.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
<div class="container content">
<h1> Parcel Details  </h1>
<br>
<h1>Parcel {{ object.id }}</h1>
<p> from : {{ object.sender_name }} {{ object.sender_surname }}</p>
<p> Parcel Price: {{ object.price }}</p>
<p> Address From: {{ object.from_address }}</p>
<p> Address To: {{ object.to_address }}</p>
<p> Parcel Type: {{ object.get_parcel_type_display  }}</p>
<br>
    <a href="{% url 'index' %}"
                   class="mt-4 btn btn-primary" style="margin: 10px;"> На главную </a>
  <a href="{% url 'parcels_list' %}"
               class="mt-4 btn btn-primary" style="margin: 10px;">К списку</a>
  <a href="{% url 'parcel_update' object.id %}"
               class="mt-4 btn btn-primary" style="margin: 10px;">Редактировать</a>
  <a href="{% url 'parcel_delete' object.id %}"
               class="mt-4 btn btn-primary" style="margin: 10px;">Удалить</a>
<br>
</div>
{% endblock %}

task_post/templates/mainapp/parcel_form.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
<div class="container content">
<h1> Parcel Create Form </h1>
<br>


<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input class="mt-4 btn btn-primary" style="margin: 10px;" type="submit" value="Создать">
     <a href="{% url 'parcels_list' %}"
                   class="mt-4 btn btn-primary" style="margin: 10px;"> Отменить </a>
</form>
</div>
{% endblock %}

task_post/templates/mainapp/parcel_list.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block content %}
<div class="container content">
  <h1>Parcel List</h1>
<br>
  {% if parcel_list %}
    <ul>
      {% for parcel in parcel_list %}
      <li>
        <a href="{% url 'parcel_view' parcel.id  %}"> Parcel {{parcel.id}}     from: {{ parcel.sender_name }} {{ parcel.sender_surname }}</a>
        ({{parcel.get_parcel_type_display }})
      </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no parcels to show.</p>
  {% endif %}
   <a href="{% url 'parcel_create' %}"
               class="mt-4 btn btn-primary" style="margin: 10px;">Новая Посылка</a>
    <a href="{% url 'index' %}"
                   class="mt-4 btn btn-primary" style="margin: 10px;"> На главную </a>
</div>
{% endblock %}

task_post/templates/mainapp/parcel_update_form.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
<div class="container content">
<h1> Parcel Update Form </h1>
<br/>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input class="mt-4 btn btn-primary" style="margin: 10px;" type="submit" value="Сохранить">
     <a href="{% url 'parcels_list' %}"
                   class="mt-4 btn btn-primary" style="margin: 10px;"> Отменить </a>
</form>
</div>
{% endblock %}